### PR TITLE
Fix to some warnings during build time

### LINKED ISSUE #57: [kinetic-devel] Build has never succeeded on ROS buildfarm
(Maybe) since its release into ROS Kinetic https://github.com/ros/rosdistro/pull/13689, I'm afraid `uwsim` might have never been built on buildfarm. At least AFAI see, the last 30 trials all failed (link to Jenkins [for 64bit](http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__uwsim__ubuntu_xenial_amd64__binary/), [for 32b](http://build.ros.org/view/Kbin_uX32/job/Kbin_uX32__uwsim__ubuntu_xenial_i386__binary/)).

Looking at its build log, [e.g. this](http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__uwsim__ubuntu_xenial_amd64__binary/172/consoleFull), I found a lot of errors happening around `libxml++-2.6`, e.g.:
```
23:41:46 /usr/include/libxml++-2.6/libxml++/exceptions/validity_error.h:36:19: error: expected ‘;’ at end of member declaration
23:41:46    ~validity_error() noexcept override;
23:41:46                    ^
23:41:46 /usr/include/libxml++-2.6/libxml++/exceptions/validity_error.h:36:21: error: ‘noexcept’ does not name a type
23:41:46    ~validity_error() noexcept override;
23:41:46                      ^
23:41:46 /usr/include/libxml++-2.6/libxml++/exceptions/validity_error.h:36:21: note: C++11 ‘noexcept’ only available with -std=c++11 or -std=gnu++11
23:41:46 /usr/include/libxml++-2.6/libxml++/exceptions/validity_error.h:38:16: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
23:41:46    void Raise() const override;
23:41:46                 ^
23:41:46 /usr/include/libxml++-2.6/libxml++/exceptions/validity_error.h:39:22: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
:
23:41:46 /usr/include/libxml++-2.6/libxml++/schema.h:48:40: error: ‘nullptr’ was not declared in this scope
```

### PR DESCRIPTION
**Pull request by 130s**
- <s>Update CI config using [industrial_ci](https://github.com/ros-industrial/industrial_ci), a set of CI scripts that can also covers [ROS prerelease test](http://wiki.ros.org/regression_tests#Running_prerelease_test).</s>
- Trying to fix #57.
  - `libxml` issue might have been solved in https://github.com/130s/underwater_simulation/commit/95c24c0f41452ffd753dfc64e0d1eaaecf6dd83d.
  - Then on Travis, I've started see another issues that were not seen prior to the commit above. They might have not been reached yet when libxml error existed.

### CODE REVIEW

**Comment by 130s** [comment]
I've split a commit for CI updated to https://github.com/uji-ros-pkg/underwater_simulation/pull/59

**Comment by 130s** [comment]
Given the comments https://github.com/uji-ros-pkg/underwater_simulation/issues/57#issuecomment-312435026, this PR may not do anything important.
I still do think this helps removing some warnings during build. So I changed the subject.

**Comment by perezsolerj** [comment]
Does not build with catkin_make_isolated:

`fatal error: osg_interactive_markers/interactive_marker_display.h: No such file or directory
compilation terminated.`

EDIT:

Even solving this introduces additional errors in isolated build:

`CMakeFiles/setVehicleDisturbances.dir/interface_examples/setVehicleDisturbances.cpp.o: In function `vehiclePoseCallback(nav_msgs::Odometry_<std::allocator<void> > const&)':
setVehicleDisturbances.cpp:(.text+0xa3): undefined reference to `osg::Matrixd::setTrans(osg::Vec3d const&)'
setVehicleDisturbances.cpp:(.text+0xb2): undefined reference to `osg::Matrixd::setRotate(osg::Quat const&)'`

**Comment by perezsolerj** [comment]
Fixed in last commit

**Pull request closed without merging**
