### PR TITLE
Updating groovy-devel from master

### PR DESCRIPTION
**Pull request by marioprats**
This PR should make groovy-devel be up to date with the latest development in master. I will do the same for hydro-devel next. We should definitely stop developing in master and do it in the latest devel devel branch (hydro now).

### CODE REVIEW

**Comment by tut-yury** [comment]
Pulled changes and compiled, everything works fine with one exception:
Header files (to write plugins) are available to other packages in the workspace only after "catkin_make install", "catkin_make" is not enough... Is this by design or it can be fixed?

**Comment by tut-yury** [comment]
Correction, headers are not available in devel/includes after install too, during development install space is not checked...
As a temporary workaround I use (in CMakeLists.txt):
include_directories(
  ${uwsim_SOURCE_DIR}/src

**Comment by marioprats** [comment]
Thanks a lot for checking it out @tut-yury 
I don't have a setup where I can easily test a package depending on uwsim. Could you please try adding "INCLUDE_DIRS src" to the uwsim catkin package (in uwsim/CMakeLists.txt) and see if that solves the problem? Should be something like this:

```
 catkin_package(
  INCLUDE_DIRS src
  LIBRARIES
    uwsim
    ...
```

If that doesn't work I'm afraid we would need to move all the header files into an include/ directory, which is what we should be doing anyway ;)

Thx!

**Comment by marioprats** [comment]
Nevermind! I have moved all the header files into the include/ folder. Let me know if it works. Thx!

**Comment by tut-yury** [comment]
That's perfect!
The only note I have now is I get a following warning during build:

/home/yury/catkin_ws/src/underwater_simulation/uwsim/src/ROSInterface.cpp: In constructor ‘ROSOdomToPAT::ROSOdomToPAT(osg::Group_, std::string, std::string, double_, int, double)’:
/home/yury/catkin_ws/src/underwater_simulation/uwsim/src/ROSInterface.cpp:83:46: warning: large integer implicitly truncated to unsigned type [-Woverflow]
/home/yury/catkin_ws/src/underwater_simulation/uwsim/src/ROSInterface.cpp:85:42: warning: large integer implicitly truncated to unsigned type [-Woverflow]

**Comment by marioprats** [comment]
Fixed. Please @perezsolerj have a look to it, I replaced the long ints by shorts, but not sure if I messed up something with the pattern types.

I'm also getting a mutex assertion when closing uwsim:

```
uwsim_binary: /usr/include/boost/thread/pthread/pthread_mutex_scoped_lock.hpp:26: boost::pthread::pthread_mutex_scoped_lock::pthread_mutex_scoped_lock(pthread_mutex_t*): Assertion `!pthread_mutex_lock(m)' failed
```

Here the backtrace, seems related to the plugin unload:

```
#0  0x00007ffff5b91425 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff5b94b8b in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff5b8a0ee in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff5b8a192 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff4e8d840 in ?? () from /opt/ros/groovy/lib/libclass_loader.so
#5  0x00007ffff4e9198e in class_loader::class_loader_private::unloadLibrary(std::string const&, class_loader::ClassLoader*) () from /opt/ros/groovy/lib/libclass_loader.so
#6  0x00007ffff4e8e353 in class_loader::ClassLoader::unloadLibraryInternal(bool) () from /opt/ros/groovy/lib/libclass_loader.so
#7  0x00007ffff4e9688e in class_loader::MultiLibraryClassLoader::unloadLibrary(std::string const&) () from /opt/ros/groovy/lib/libclass_loader.so
#8  0x00007ffff4e96904 in class_loader::MultiLibraryClassLoader::shutdownAllClassLoaders() () from /opt/ros/groovy/lib/libclass_loader.so
#9  0x00007ffff4e969d4 in class_loader::MultiLibraryClassLoader::~MultiLibraryClassLoader() () from /opt/ros/groovy/lib/libclass_loader.so
#10 0x00007ffff7b10083 in pluginlib::ClassLoader<uwsim::SimulatedDeviceFactory>::~ClassLoader() () from /home/mprats/ros/uwsim_ws/install_isolated/lib/libuwsim.so
#11 0x00007ffff5b96d1d in __cxa_finalize () from /lib/x86_64-linux-gnu/libc.so.6
#12 0x00007ffff7a598b6 in __do_global_dtors_aux () from /home/mprats/ros/uwsim_ws/install_isolated/lib/libuwsim.so
#13 0x00007fffffffd730 in ?? ()
#14 0x00007fffffffdd70 in ?? ()
#15 0x00007ffff7b49601 in _fini () from /home/mprats/ros/uwsim_ws/install_isolated/lib/libuwsim.so
#16 0x00007fffffffdd70 in ?? ()
#17 0x00007ffff7de992d in ?? () from /lib64/ld-linux-x86-64.so.2
```

**Comment by tut-yury** [comment]
Made a new commit my repository that fixes that error, you can pul it from there...
Now I only get the good old warning "Inconsistency detected by ld.so: dl-close.c: 759: _dl_close: Assertion `map->l_init_called' failed!". As far as I know this is OS bug in 12.04....

**Comment by perezsolerj** [comment]
@marioprats works as it should. I wrote long ints just to show in a more "user-friendly" way how it works, just in case someone wants to create it's own pattern. But, anyway, something like that can't be called user-friendly :).

I'm sorry but I can't help with the rest by the moment. I guess we will be ready to migrate to Groovy , or hydro soon and leave fuerte branch...

**Comment by tut-yury** [comment]
It looks fine from my side too, using the latest commit from my repository (https://github.com/tut-yury/underwater_simulation/tree/groovy-devel).
So, I think the code is ready for merge....

**Comment by marioprats** [comment]
ok, cherry-picking and merging. Thx!

**Pull request merged**
